// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/threejs/three-shaderpass.d.ts
declare namespace THREE {
	export class ShaderPass {
		constructor( shader: Shader, textureID?: string );

		textureID: string;
		uniforms: any;
		material: ShaderMaterial;
		renderToScreen: boolean;
		enabled: boolean;
		needsSwap: boolean;
		clear: boolean;
		camera: Camera;
		scene: Scene;
		quad: Mesh;

		render(renderer: WebGLRenderer, writeBuffer: WebGLRenderTarget, readBuffer: WebGLRenderTarget, delta: number): void;
	}
}