mysql:
  image: mysql:latest
  container_name: dreamsark_database
  ports:
    - 3306:3306
  environment:
    MYSQL_DATABASE: dreamsark
    MYSQL_ROOT_PASSWORD: 123456

php:
  build: .
  dockerfile: ./build/docker/php/Dockerfile
  container_name: dreamsark_php
  volumes:
    - .:/var/www/dreamsark
  entrypoint:
    - php-fpm

regis:
  image: redis:alpine
  container_name: dreamsark_redis

node:
  build: .
  dockerfile: ./build/docker/node/Dockerfile
#  image: node:latest
  container_name: dreamsark_node
  volumes:
    - .:/src
  working_dir: /src
  links:
    - regis
  ports:
    - 3333:3333
  entrypoint: top -b

nginx:
  image: nginx:alpine
  container_name: dreamsark_nginx
  volumes_from:
    - php
  volumes:
    - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
    - regis
  ports:
    - 8080:80
