// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/threejs/three-copyshader.d.ts
declare namespace THREE {
	export var CopyShader: Shader;
}