// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/threejs/three-renderpass.d.ts
declare namespace THREE {
	export class RenderPass {
		constructor( scene: Scene, camera: Camera, overrideMaterial?: Material, clearColor?: Color, clearAlpha?: number );
		constructor( scene: Scene, camera: Camera, overrideMaterial?: Material, clearColor?: string, clearAlpha?: number );
		constructor( scene: Scene, camera: Camera, overrideMaterial?: Material, clearColor?: number, clearAlpha?: number );

		scene: Scene;
		camera: Camera;
		overrideMaterial: Material;
		clearColor: any; // Color or string or number
		clearAlpha: number;
		oldClearColor: Color;
		oldClearAlpha: number;
		enabled: boolean;
		clear: boolean;
		needsSwap: boolean;

        render(renderer: WebGLRenderer, writeBuffer: WebGLRenderTarget, readBuffer: WebGLRenderTarget, delta: number): void;
	}
}
